In [2]:
import pandas as pd

In [3]:
marks=pd.read_csv('C:/Users/Lenovo/Downloads/StudentsPerformance.csv')

In [4]:
print(type(marks))
marks

<class 'pandas.DataFrame'>

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [5]:
print(marks.shape)
print(marks.columns)
print(marks.dtypes)

(1000, 8)
Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='str')
gender                           str
race/ethnicity                   str
parental level of education      str
lunch                            str
test preparation course          str
math score                     int64
reading score                  int64
writing score                  int64
dtype: object

In [6]:
marks.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [7]:
med=pd.read_csv('C:/Users/Lenovo/Downloads/insurance.csv')

In [8]:
med.info()
print(med.shape)

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB
(1338, 7)

In [9]:
road=pd.read_csv('C:/Users/Lenovo/Downloads/automobile_dataset.csv')

In [10]:
print(road.shape)
print(road.columns)
print(road.dtypes)
type(road)

(5500, 18)
Index(['Make', 'Model', 'Year', 'Fuel_Type', 'Transmission', 'Engine_Size',
       'Mileage', 'Horsepower', 'Torque', 'Owners', 'Accident_History',
       'Service_History', 'Color', 'Body_Type', 'Drivetrain',
       'Fuel_Efficiency', 'Location', 'Selling_Price'],
      dtype='str')
Make                    str
Model                   str
Year                  int64
Fuel_Type               str
Transmission            str
Engine_Size         float64
Mileage               int64
Horsepower          float64
Torque              float64
Owners                int64
Accident_History    float64
Service_History         str
Color                   str
Body_Type               str
Drivetrain              str
Fuel_Efficiency     float64
Location                str
Selling_Price         int64
dtype: object

pandas.DataFrame

In [11]:
print(road.info())

<class 'pandas.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Make              5500 non-null   str
 1   Model             5500 non-null   str
 2   Year              5500 non-null   int64
 3   Fuel_Type         5500 non-null   str
 4   Transmission      4673 non-null   str
 5   Engine_Size       4656 non-null   float64
 6   Mileage           5500 non-null   int64
 7   Horsepower        4700 non-null   float64
 8   Torque            4701 non-null   float64
 9   Owners            5500 non-null   int64
 10  Accident_History  4688 non-null   float64
 11  Service_History   4645 non-null   str
 12  Color             4697 non-null   str
 13  Body_Type         5500 non-null   str
 14  Drivetrain        5500 non-null   str
 15  Fuel_Efficiency   4706 non-null   float64
 16  Location          4718 non-null   str
 17  Selling_Price     5500 non-null   int64
dtypes: float64(5), int64(4), str(9)
memory usage: 773.6 KB
None

In [12]:
road.drop_duplicates(inplace=True)

In [13]:
print(road.head())

            Make   Model  Year Fuel_Type Transmission  Engine_Size  Mileage  \
0  Mercedes-Benz     GLE  2024    Petrol    Automatic          2.3      100
1        Hyundai  Tucson  2008    Petrol    Automatic          2.3   387035
2     Volkswagen    Golf  2021    Hybrid          NaN          1.9    46054
3      Chevrolet   Tahoe  2005    Petrol          NaN          2.2   141302
4         Toyota   Camry  2022    Petrol    Automatic          1.9    32813

   Horsepower  Torque  Owners  Accident_History  Service_History   Color  \
0       186.0   196.0       1               0.0              NaN  Silver
1       189.0   190.0       4               0.0              NaN    Blue
2       158.0   153.0       1               0.0  Partial Service    Gray
3       169.0   165.0       5               1.0       No Service    Blue
4       149.0   141.0       1               0.0     Full Service   Brown

   Body_Type Drivetrain  Fuel_Efficiency Location  Selling_Price
0        SUV        AWD             30.0       IL          64140
1        SUV        FWD             35.0       FL            500
2  Hatchback        AWD             43.0       NY          16429
3        SUV        AWD              NaN       FL           2199
4      Sedan        FWD             38.0       CA          21792

In [14]:
print(road.describe())

              Year  Engine_Size        Mileage   Horsepower       Torque  \
count  5500.000000  4656.000000    5500.000000  4700.000000  4701.000000
mean   2014.494000     2.450623  114529.481636   198.236596   189.014678
std       5.789745     0.843913   91858.943421    55.678165    56.631309
min    2005.000000     0.000000     100.000000    97.000000    77.000000
25%    2009.000000     2.000000   39112.000000   160.000000   151.000000
50%    2014.000000     2.400000   96926.500000   187.000000   178.000000
75%    2020.000000     3.000000  172757.500000   231.000000   219.000000
max    2024.000000     5.700000  536731.000000   434.000000   443.000000

            Owners  Accident_History  Fuel_Efficiency  Selling_Price
count  5500.000000       4688.000000      4706.000000    5500.000000
mean      2.464000          0.408063        34.179771   12319.873636
std       1.280022          0.491527        15.085473   12658.478862
min       1.000000          0.000000        10.000000     500.000000
25%       1.000000          0.000000        27.000000    1304.750000
50%       2.000000          0.000000        32.000000    8586.000000
75%       3.000000          1.000000        37.000000   19097.500000
max       5.000000          1.000000       141.000000   86692.000000

In [15]:
road["Horsepower"].mean()

np.float64(198.23659574468084)

In [16]:
road.isnull().sum()

Make                  0
Model                 0
Year                  0
Fuel_Type             0
Transmission        827
Engine_Size         844
Mileage               0
Horsepower          800
Torque              799
Owners                0
Accident_History    812
Service_History     855
Color               803
Body_Type             0
Drivetrain            0
Fuel_Efficiency     794
Location            782
Selling_Price         0
dtype: int64

In [17]:
road["Fuel_Efficiency"] = road["Fuel_Efficiency"].fillna(road["Fuel_Efficiency"].mean())

In [18]:
road.isnull().sum()

Make                  0
Model                 0
Year                  0
Fuel_Type             0
Transmission        827
Engine_Size         844
Mileage               0
Horsepower          800
Torque              799
Owners                0
Accident_History    812
Service_History     855
Color               803
Body_Type             0
Drivetrain            0
Fuel_Efficiency       0
Location            782
Selling_Price         0
dtype: int64

In [19]:
road["Accident_History"]=road["Accident_History"].mean()

In [20]:
road["Transmission"].mode()

0    Automatic
Name: Transmission, dtype: str

In [21]:
road["Transmission"]=road["Transmission"].fillna(road["Transmission"].mode()[0])

In [22]:
road.isnull().sum()

Make                  0
Model                 0
Year                  0
Fuel_Type             0
Transmission          0
Engine_Size         844
Mileage               0
Horsepower          800
Torque              799
Owners                0
Accident_History      0
Service_History     855
Color               803
Body_Type             0
Drivetrain            0
Fuel_Efficiency       0
Location            782
Selling_Price         0
dtype: int64

In [23]:
road.dropna(inplace=True)

first i dropped all the duplicates next i filled all the fuel efficiency feild with  the mean then i corrected it and filled only the null then i did the same for accident history field then i got the mode[0] for the transmission field and filled the null with it then i dropped everything else still null (service history,color,engine size,location)

In [24]:
road.head()

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price
2,Volkswagen,Golf,2021,Hybrid,Automatic,1.9,46054,158.0,153.0,1,0.408063,Partial Service,Gray,Hatchback,AWD,43.000000,NY,16429
3,Chevrolet,Tahoe,2005,Petrol,Automatic,2.2,141302,169.0,165.0,5,0.408063,No Service,Blue,SUV,AWD,34.179771,FL,2199
4,Toyota,Camry,2022,Petrol,Automatic,1.9,32813,149.0,141.0,1,0.408063,Full Service,Brown,Sedan,FWD,38.000000,CA,21792
7,Mercedes-Benz,C-Class,2022,Petrol,Automatic,2.3,32133,180.0,162.0,1,0.408063,Partial Service,Green,Sedan,FWD,35.000000,NY,31416
9,Honda,Pilot,2020,Hybrid,Automatic,2.1,12494,178.0,168.0,1,0.408063,No Service,Blue,SUV,FWD,44.000000,NC,22311

In [25]:
#vehicles that has more than 2 owners
road[road["Owners"] > 2]

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price
3,Chevrolet,Tahoe,2005,Petrol,Automatic,2.2,141302,169.0,165.0,5,0.408063,No Service,Blue,SUV,AWD,34.179771,FL,2199
15,Mercedes-Benz,C-Class,2010,Petrol,Manual,2.0,17138,169.0,160.0,3,0.408063,Partial Service,Blue,Sedan,FWD,27.000000,NC,11728
17,Chevrolet,Tahoe,2011,Petrol,Automatic,3.3,264441,258.0,252.0,4,0.408063,Partial Service,Gray,SUV,AWD,22.000000,TX,3395
28,Ford,Mustang,2010,Diesel,Automatic,3.1,34292,245.0,238.0,3,0.408063,Partial Service,Brown,Coupe,RWD,23.000000,FL,5739
33,Hyundai,Santa Fe,2009,Petrol,Automatic,3.2,159873,239.0,219.0,4,0.408063,No Service,Brown,SUV,RWD,31.000000,NY,857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5464,Ford,F-150,2010,Petrol,Automatic,5.0,197288,366.0,356.0,4,0.408063,No Service,Red,Truck,4WD,16.000000,TX,500
5467,BMW,X3,2010,Diesel,Automatic,3.3,205389,246.0,226.0,4,0.408063,Full Service,Black,SUV,FWD,19.000000,OH,2996
5478,Audi,A6,2010,Petrol,Manual,2.1,155818,169.0,176.0,3,0.408063,Full Service,Red,Sedan,FWD,41.000000,FL,9714
5481,Hyundai,Elantra,2019,Petrol,Automatic,2.1,69473,170.0,179.0,3,0.408063,Full Service,Silver,Sedan,AWD,35.000000,GA,10226
5496,Nissan,Pathfinder,2006,Petrol,Automatic,3.1,287332,243.0,227.0,5,0.408063,No Service,Gray,SUV,AWD,34.179771,NY,500

In [26]:
road.iloc[:7]

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price
2,Volkswagen,Golf,2021,Hybrid,Automatic,1.9,46054,158.0,153.0,1,0.408063,Partial Service,Gray,Hatchback,AWD,43.000000,NY,16429
3,Chevrolet,Tahoe,2005,Petrol,Automatic,2.2,141302,169.0,165.0,5,0.408063,No Service,Blue,SUV,AWD,34.179771,FL,2199
4,Toyota,Camry,2022,Petrol,Automatic,1.9,32813,149.0,141.0,1,0.408063,Full Service,Brown,Sedan,FWD,38.000000,CA,21792
7,Mercedes-Benz,C-Class,2022,Petrol,Automatic,2.3,32133,180.0,162.0,1,0.408063,Partial Service,Green,Sedan,FWD,35.000000,NY,31416
9,Honda,Pilot,2020,Hybrid,Automatic,2.1,12494,178.0,168.0,1,0.408063,No Service,Blue,SUV,FWD,44.000000,NC,22311
12,Toyota,RAV4,2019,Diesel,Automatic,3.1,66811,233.0,211.0,1,0.408063,Partial Service,Brown,SUV,AWD,25.000000,OH,14479
15,Mercedes-Benz,C-Class,2010,Petrol,Manual,2.0,17138,169.0,160.0,3,0.408063,Partial Service,Blue,Sedan,FWD,27.000000,NC,11728

In [27]:
road.loc[road["Year"]<2022]

,Make,Model,Year,Fuel_Type,Transmission,Engine_Size,Mileage,Horsepower,Torque,Owners,Accident_History,Service_History,Color,Body_Type,Drivetrain,Fuel_Efficiency,Location,Selling_Price
2,Volkswagen,Golf,2021,Hybrid,Automatic,1.9,46054,158.0,153.0,1,0.408063,Partial Service,Gray,Hatchback,AWD,43.000000,NY,16429
3,Chevrolet,Tahoe,2005,Petrol,Automatic,2.2,141302,169.0,165.0,5,0.408063,No Service,Blue,SUV,AWD,34.179771,FL,2199
9,Honda,Pilot,2020,Hybrid,Automatic,2.1,12494,178.0,168.0,1,0.408063,No Service,Blue,SUV,FWD,44.000000,NC,22311
12,Toyota,RAV4,2019,Diesel,Automatic,3.1,66811,233.0,211.0,1,0.408063,Partial Service,Brown,SUV,AWD,25.000000,OH,14479
15,Mercedes-Benz,C-Class,2010,Petrol,Manual,2.0,17138,169.0,160.0,3,0.408063,Partial Service,Blue,Sedan,FWD,27.000000,NC,11728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5482,Mercedes-Benz,GLC,2014,Diesel,Automatic,2.0,215782,177.0,180.0,2,0.408063,Full Service,Red,SUV,AWD,34.179771,TX,7325
5491,Nissan,Pathfinder,2020,Petrol,Automatic,2.7,79498,212.0,204.0,1,0.408063,Partial Service,Gray,SUV,AWD,24.000000,OH,18345
5496,Nissan,Pathfinder,2006,Petrol,Automatic,3.1,287332,243.0,227.0,5,0.408063,No Service,Gray,SUV,AWD,34.179771,NY,500
5497,BMW,X3,2013,Petrol,Automatic,2.2,95961,171.0,152.0,2,0.408063,No Service,Blue,SUV,AWD,32.000000,MI,9882
5498,Volkswagen,Golf,2020,Hybrid,Automatic,1.5,56643,135.0,125.0,2,0.408063,No Service,White,Hatchback,FWD,57.000000,NY,10474

In [28]:
road_by_year=road.groupby("Year")

In [29]:
road_by_year[["Engine_Size","Mileage"]].mean()

      Engine_Size        Mileage
Year
2005     2.650400  229467.448000
2006     2.517347  212244.887755
2007     2.420388  190669.029126
2008     2.545000  188965.730000
2009     2.478218  185513.722772
2010     2.536792  157492.216981
2011     2.599000  170354.360000
2012     2.426050  138878.142857
2013     2.413131  132044.181818
2014     2.463736  120104.758242
2015     2.199020  104742.529412
2016     2.640000   96885.536842
2017     2.443158   87786.168421
2018     2.373267   77167.039604
2019     2.340196   56861.931373
2020     2.436036   49550.900901
2021     2.333077   37032.369231
2022     2.294949   26529.909091
2023     2.505042   13313.546218
2024     2.436364    2123.434343

this is a subset grouped by year each year appears the vehicles in that year its average engine size and its average mileage